import css from './ProfilePage.module.css';
// import type { Metadata } from 'next';

// export const metadata: Metadata = {
//   title: 'NoteHub profile page',
//   description: 'NoteHub for managing  notes, generated by Anna Dzh',
//   keywords: ['notes', 'note manager', 'note organizer', 'productivity', 'search notes'],
//   icons: {
//     icon: '/favicon.svg',
//   },
//   openGraph: {
//     title: 'NoteHub - Smart Note Management',
//     description:
//       'An app for managing your notes and reminders with tags based on your areas of work  or another part of life',
//     url: 'https://08-zustand-three-cyan.vercel.app/',
//     images: [
//       {
//         url: 'https://ac.goit.global/fullstack/react/og-meta.jpg',
//         width: 1200,
//         height: 630,
//         alt: 'NoteHub Notes App',
//       },
//     ],
//     type: 'website',
//   },
// };
export default function Profile() {
  return (
    <main className={css.mainContent}>
      <div className={css.profileCard}>
        <div className={css.header}>
          <h1 className={css.formTitle}>Profile Page</h1>
          {/* <a src="" className={css.editProfileButton}>
            Edit Profile
          </a> */}
        </div>
        <div className={css.avatarWrapper}>
          <img src="Avatar" alt="User Avatar" width={120} height={120} className={css.avatar} />
        </div>
        <div className={css.profileInfo}>
          <p>Username: your_username</p>
          <p>Email: your_email@example.com</p>
        </div>
      </div>
    </main>
  );
}
//add meta
